export { declension } from './declension'
export * from './device'
export { emitEvent } from './emitEvent'
export { getScrollbarWidth } from './getScrollbarWidth'
export { setViewportHeight } from './setViewportHeight'
