export * as DOM from './dom'

export { default as Device } from './device'
export { default as declension } from './declension'
export { default as getPageQuery } from './getPageQuery'
export { default as getScrollbarWidth } from './getScrollbarWidth'
export { default as getSection } from './getSection'
export { default as scrollTo } from './scrollTo'
export { default as setViewportHeight } from './setViewportHeight'
export { default as smoothScroll } from './smoothScroll'
