// import './animation'
// import './calendar'
// import './file'
import './font'
import './gallery'
import './inputmask'
import './lazyload'
import './map'
import './scrollbooster'
import './scrollto'
import './slider'
// import './tooltip'
